# $FreeBSD$

#SUBDIR=	iwx22000-QU-B-HR-Bfw \
#	iwx22000-QU-B-JF-Bfw \
#	iwx22000-QU-C-HR-Cfw \
#	iwx22000-QU-C-JF-Bfw \
#	iwx22000-QUZ-A-HR-Bfw \
#	iwx22000-QUZ-A-JF-Bfw \
3	iwx22560-cc-a0fw

SUBDIR= iwxfw
.include <bsd.subdir.mk>
	
