# $FreeBSD$

KMOD=	iwx22000fw
#IMG=	iwlwifi-cc-a0-46
#IMG=	intel_iwlwifi-cc-a0-46

#IMG=	kernelorg-iwlwifi_iwlwifi-cc-a0-50
IMG=	openbsd_iwx-cc-a0-46

#IMG=	chromiumos_iwlwifi-cc-a0-46
#IMG=	chromiumos_iwlwifi-cc-a0-50
#IMG=	chromiumos_iwlwifi-cc-a0-53
.include <bsd.kmod.mk>

