# $FreeBSD$

KMOD=	iwx22000fw
# iwx_run_init_ucode() returns '35'
#IMG=	iwlwifi-cc-a0-46
# source: https://www.intel.com/content/www/us/en/support/articles/000005511/network-and-i-o/wireless-networking.html
# iwx_run_init_ucode() returns '35'
#IMG=	intel_iwlwifi-cc-a0-46

# source: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
# iwx_run_init_ucode() returns '35'
#IMG=	kernelorg-firmware_iwlwifi-cc-a0-46
# iwx_read_firmware() returns 22, section 16777216
#IMG=	kernelorg-firmware_iwlwifi-cc-a0-48

# source: https://git.kernel.org/pub/scm/linux/kernel/git/iwlwifi/linux-firmware.git
# iwx_read_firmware() returns 22, section 16777221
#IMG=	kernelorg-iwlwifi_iwlwifi-cc-a0-50
# iwx_run_init_ucode() returns '35'
IMG=	openbsd_iwx-cc-a0-46

# source: https://chromium.googlesource.com/chromiumos/third_party/linux-firmware
# iwx_run_init_ucode() returns '35'
#IMG=	chromiumos_iwlwifi-cc-a0-46
# iwx_read_firmware() returns 22, section 16777221
#IMG=	chromiumos_iwlwifi-cc-a0-50
# iwx_read_firmware() returns 22, section 16777221
#IMG=	chromiumos_iwlwifi-cc-a0-53
.include <bsd.kmod.mk>

